{% set name = "rmsd" %}
{% set version = "1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 16a84a5f919faa0f2361e55ad4009a7c28e19a21ee9cc3bdb83f28ffb566563f

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - calculate_rmsd = rmsd.calculate_rmsd:main

requirements:
  host:
    - python
    - pip
  run:
    - python
    - numpy
    - scipy

test:
  imports:
    - rmsd
  commands:
    - calculate_rmsd --help

about:
  home: https://github.com/charnley/rmsd
  license: BSD 2-clause
  license_family: BSD
  license_file: LICENSE
  summary: Calculate Root-mean-square deviation (RMSD) of two molecules

  description: |
    Calculate root-mean-square deviation (RMSD) between two sets of cartesian
    coordinates (XYZ or PDB format), using rotation (fx. Kabsch algorithm),
    atom reordering (fx. Hungarian algorithm), and axis reflections,
    resulting in the minimal RMSD.
  doc_url: https://github.com/charnley/rmsd
  dev_url: https://github.com/charnley/rmsd

extra:
  recipe-maintainers:
    - jaimergp
